[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.17"
optimizer = true
optimizer_runs = 1000000
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@uniswap/v3-core/=lib/v3-core/',
    '@uniswap/v3-periphery/=lib/v3-periphery/',
    '@reservoir/=lib/oracle/contracts'
]
fs_permissions = [{ access = "read", path = "./"}]